"""Default word lists for CanvasClash mode organized by category and difficulty."""

from __future__ import annotations

from scribbl_py.game.types import DifficultyLevel, WordCategory

# Type alias for word list structure
WordLists = dict[WordCategory, dict[DifficultyLevel, list[str]]]

DEFAULT_WORD_LISTS: WordLists = {
    WordCategory.ANIMALS: {
        DifficultyLevel.EASY: [
            "cat",
            "dog",
            "fish",
            "bird",
            "cow",
            "pig",
            "duck",
            "frog",
            "bear",
            "lion",
            "tiger",
            "mouse",
            "horse",
            "sheep",
            "chicken",
            "rabbit",
            "turtle",
            "snake",
            "monkey",
            "elephant",
        ],
        DifficultyLevel.MEDIUM: [
            "penguin",
            "dolphin",
            "giraffe",
            "zebra",
            "kangaroo",
            "koala",
            "panda",
            "raccoon",
            "squirrel",
            "hedgehog",
            "flamingo",
            "peacock",
            "parrot",
            "octopus",
            "jellyfish",
            "butterfly",
            "ladybug",
            "dragonfly",
            "seahorse",
            "hamster",
        ],
        DifficultyLevel.HARD: [
            "platypus",
            "narwhal",
            "axolotl",
            "pangolin",
            "tapir",
            "quokka",
            "capybara",
            "armadillo",
            "chameleon",
            "iguana",
            "orangutan",
            "chimpanzee",
            "rhinoceros",
            "hippopotamus",
            "crocodile",
            "alligator",
            "salamander",
            "meerkat",
            "wolverine",
            "lemur",
        ],
    },
    WordCategory.OBJECTS: {
        DifficultyLevel.EASY: [
            "ball",
            "book",
            "chair",
            "table",
            "door",
            "window",
            "cup",
            "spoon",
            "fork",
            "knife",
            "plate",
            "clock",
            "lamp",
            "bed",
            "phone",
            "key",
            "box",
            "pencil",
            "paper",
            "bottle",
        ],
        DifficultyLevel.MEDIUM: [
            "umbrella",
            "backpack",
            "suitcase",
            "camera",
            "guitar",
            "piano",
            "bicycle",
            "skateboard",
            "telescope",
            "microscope",
            "compass",
            "magnet",
            "battery",
            "flashlight",
            "candle",
            "mirror",
            "calendar",
            "envelope",
            "scissors",
            "hammer",
        ],
        DifficultyLevel.HARD: [
            "metronome",
            "abacus",
            "sextant",
            "astrolabe",
            "theodolite",
            "barometer",
            "hygrometer",
            "stethoscope",
            "thermometer",
            "kaleidoscope",
            "periscope",
            "stereoscope",
            "hourglass",
            "sundial",
            "gramophone",
            "typewriter",
            "telegraph",
            "sewing machine",
            "loom",
            "anvil",
        ],
    },
    WordCategory.ACTIONS: {
        DifficultyLevel.EASY: [
            "run",
            "jump",
            "walk",
            "sit",
            "sleep",
            "eat",
            "drink",
            "dance",
            "sing",
            "laugh",
            "cry",
            "smile",
            "wave",
            "clap",
            "swim",
            "climb",
            "crawl",
            "throw",
            "catch",
            "kick",
        ],
        DifficultyLevel.MEDIUM: [
            "juggle",
            "skateboard",
            "snowboard",
            "whistle",
            "meditate",
            "exercise",
            "stretch",
            "knit",
            "paint",
            "draw",
            "photograph",
            "garden",
            "bake",
            "cook",
            "sweep",
            "vacuum",
            "hammer",
            "saw",
            "drill",
            "measure",
        ],
        DifficultyLevel.HARD: [
            # Drawable actions
            "somersault",
            "cartwheel",
            "backflip",
            "handstand",
            "tightrope walk",
            "parallel park",
            "origami",
            "calligraphy",
            "ventriloquism",
            "sleepwalk",
            "moonwalk",
            "breakdance",
            "juggling fire",
            "sword swallowing",
            "limbo dance",
            "hula hoop",
            "bungee jump",
            "skydiving",
            "scuba diving",
            "arm wrestling",
        ],
    },
    WordCategory.PLACES: {
        DifficultyLevel.EASY: [
            "house",
            "school",
            "park",
            "beach",
            "forest",
            "city",
            "farm",
            "zoo",
            "store",
            "library",
            "hospital",
            "airport",
            "church",
            "museum",
            "bank",
            "office",
            "hotel",
            "restaurant",
            "playground",
            "garden",
        ],
        DifficultyLevel.MEDIUM: [
            "aquarium",
            "observatory",
            "cathedral",
            "lighthouse",
            "windmill",
            "pyramid",
            "castle",
            "palace",
            "volcano",
            "waterfall",
            "canyon",
            "desert",
            "rainforest",
            "tundra",
            "savanna",
            "archipelago",
            "peninsula",
            "valley",
            "plateau",
            "glacier",
        ],
        DifficultyLevel.HARD: [
            "colosseum",
            "acropolis",
            "pantheon",
            "mausoleum",
            "ziggurat",
            "pagoda",
            "minaret",
            "monastery",
            "basilica",
            "citadel",
            "fjord",
            "geyser",
            "caldera",
            "atoll",
            "estuary",
            "delta",
            "quarry",
            "cavern",
            "grotto",
            "labyrinth",
        ],
    },
    WordCategory.FOOD: {
        DifficultyLevel.EASY: [
            "pizza",
            "burger",
            "apple",
            "banana",
            "bread",
            "cheese",
            "milk",
            "egg",
            "rice",
            "pasta",
            "chicken",
            "fish",
            "cake",
            "cookie",
            "ice cream",
            "sandwich",
            "hot dog",
            "potato",
            "carrot",
            "tomato",
        ],
        DifficultyLevel.MEDIUM: [
            "sushi",
            "taco",
            "burrito",
            "quesadilla",
            "lasagna",
            "ravioli",
            "gnocchi",
            "croissant",
            "baguette",
            "pretzel",
            "donut",
            "muffin",
            "waffle",
            "pancake",
            "omelette",
            "avocado",
            "mango",
            "pineapple",
            "watermelon",
            "blueberry",
        ],
        DifficultyLevel.HARD: [
            "ratatouille",
            "bouillabaisse",
            "escargot",
            "foie gras",
            "coq au vin",
            "risotto",
            "osso buco",
            "tiramisu",
            "panna cotta",
            "bruschetta",
            "prosciutto",
            "baklava",
            "hummus",
            "falafel",
            "kimchi",
            "tempura",
            "edamame",
            "gazpacho",
            "paella",
            "quinoa",
        ],
    },
    WordCategory.SPORTS: {
        DifficultyLevel.EASY: [
            "soccer",
            "basketball",
            "tennis",
            "baseball",
            "football",
            "golf",
            "swimming",
            "running",
            "boxing",
            "skating",
            "skiing",
            "surfing",
            "fishing",
            "bowling",
            "volleyball",
            "hockey",
            "cycling",
            "dancing",
            "wrestling",
            "karate",
        ],
        DifficultyLevel.MEDIUM: [
            "badminton",
            "cricket",
            "lacrosse",
            "rugby",
            "polo",
            "archery",
            "fencing",
            "gymnastics",
            "diving",
            "rowing",
            "kayaking",
            "sailing",
            "rock climbing",
            "skateboarding",
            "snowboarding",
            "motocross",
            "parkour",
            "trampolining",
            "weightlifting",
            "triathlon",
        ],
        DifficultyLevel.HARD: [
            "bobsled",
            "luge",
            "skeleton",
            "curling",
            "biathlon",
            "pentathlon",
            "decathlon",
            "steeplechase",
            "pole vault",
            "javelin",
            "discus",
            "hammer throw",
            "synchronized swimming",
            "water polo",
            "handball",
            "squash",
            "racquetball",
            "jai alai",
            "sepak takraw",
            "hurling",
        ],
    },
    WordCategory.MOVIES: {
        DifficultyLevel.EASY: [
            "superhero",
            "pirate",
            "cowboy",
            "princess",
            "dragon",
            "wizard",
            "vampire",
            "zombie",
            "robot",
            "alien",
            "dinosaur",
            "monster",
            "detective",
            "spy",
            "astronaut",
            "knight",
            "ninja",
            "ghost",
            "mummy",
            "werewolf",
        ],
        DifficultyLevel.MEDIUM: [
            # Drawable movie scenes/scenarios
            "time machine",
            "space station",
            "treasure chest",
            "car chase",
            "bank heist",
            "spy disguise",
            "apocalypse",
            "magic portal",
            "crystal ball",
            "wanted poster",
            "prison escape",
            "sword fight",
            "duel at dawn",
            "haunted house",
            "flying carpet",
            "enchanted forest",
            "underwater city",
            "floating island",
            "secret passage",
            "booby trap",
        ],
        DifficultyLevel.HARD: [
            # Drawable movie/character concepts
            "mad scientist",
            "evil twin",
            "damsel in distress",
            "masked villain",
            "secret agent",
            "escaped prisoner",
            "fortune teller",
            "circus performer",
            "swamp creature",
            "giant robot",
            "invisible man",
            "time traveler",
            "frankenstein",
            "jekyll and hyde",
            "phantom of the opera",
            "count dracula",
            "captain hook",
            "grim reaper",
            "fairy godmother",
            "evil queen",
        ],
    },
    WordCategory.NATURE: {
        DifficultyLevel.EASY: [
            "tree",
            "flower",
            "grass",
            "leaf",
            "sun",
            "moon",
            "star",
            "cloud",
            "rain",
            "snow",
            "wind",
            "mountain",
            "river",
            "ocean",
            "lake",
            "rock",
            "sand",
            "dirt",
            "sky",
            "rainbow",
        ],
        DifficultyLevel.MEDIUM: [
            "waterfall",
            "volcano",
            "earthquake",
            "tornado",
            "hurricane",
            "lightning",
            "thunder",
            "avalanche",
            "landslide",
            "tsunami",
            "glacier",
            "iceberg",
            "canyon",
            "valley",
            "plateau",
            "peninsula",
            "archipelago",
            "reef",
            "moss",
            "fern",
        ],
        DifficultyLevel.HARD: [
            # Drawable nature phenomena and features
            "aurora borealis",
            "meteor shower",
            "solar eclipse",
            "lunar eclipse",
            "quicksand",
            "coral reef",
            "tidal wave",
            "whirlpool",
            "hot spring",
            "stalagmite",
            "stalactite",
            "fossil",
            "amber",
            "venus flytrap",
            "redwood tree",
            "bonsai tree",
            "cactus flower",
            "beehive",
            "ant hill",
            "spider web",
        ],
    },
    WordCategory.TECHNOLOGY: {
        DifficultyLevel.EASY: [
            "computer",
            "phone",
            "tablet",
            "keyboard",
            "mouse",
            "screen",
            "laptop",
            "camera",
            "printer",
            "speaker",
            "headphones",
            "charger",
            "battery",
            "remote",
            "television",
            "radio",
            "microphone",
            "calculator",
            "watch",
            "clock",
        ],
        DifficultyLevel.MEDIUM: [
            "smartphone",
            "smartwatch",
            "drone",
            "robot",
            "3d printer",
            "touchscreen",
            "webcam",
            "projector",
            "scanner",
            "router",
            "usb cable",
            "hard drive",
            "graphics card",
            "power strip",
            "extension cord",
            "solar panel",
            "wind turbine",
            "electric car",
            "self driving car",
            "traffic light",
        ],
        DifficultyLevel.HARD: [
            # Drawable technology items
            "hologram",
            "satellite dish",
            "radar antenna",
            "control panel",
            "circuit board",
            "floppy disk",
            "cassette tape",
            "vinyl record",
            "rotary phone",
            "pager",
            "telegraph machine",
            "crt monitor",
            "robot arm",
            "vr headset",
            "jet pack",
            "hoverboard",
            "laser gun",
            "radar screen",
            "security camera",
            "fingerprint scanner",
        ],
    },
    WordCategory.PROFESSIONS: {
        DifficultyLevel.EASY: [
            "teacher",
            "doctor",
            "nurse",
            "chef",
            "farmer",
            "police",
            "firefighter",
            "pilot",
            "driver",
            "singer",
            "dancer",
            "painter",
            "writer",
            "actor",
            "builder",
            "plumber",
            "electrician",
            "mechanic",
            "cashier",
            "waiter",
        ],
        DifficultyLevel.MEDIUM: [
            "architect",
            "engineer",
            "scientist",
            "lawyer",
            "accountant",
            "programmer",
            "designer",
            "photographer",
            "journalist",
            "veterinarian",
            "dentist",
            "pharmacist",
            "librarian",
            "curator",
            "translator",
            "interpreter",
            "detective",
            "astronaut",
            "archaeologist",
            "geologist",
        ],
        DifficultyLevel.HARD: [
            "anesthesiologist",
            "cardiologist",
            "neurosurgeon",
            "orthopedist",
            "radiologist",
            "epidemiologist",
            "marine biologist",
            "astrophysicist",
            "quantum physicist",
            "paleontologist",
            "anthropologist",
            "ethnographer",
            "cartographer",
            "cryptographer",
            "actuary",
            "sommelier",
            "taxidermist",
            "ornithologist",
            "ichthyologist",
            "entomologist",
        ],
    },
}
